<?php
/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * THIS IS MODIFIED FOR YOUZAN, ANY PROBLEM PLS CONTACT lanhu(zhangyuanhao@qima-inc.com)
 * qingjiao(qingjiao@qima-inc.com) & xiao'er(shiyu@qima-inc.com)
 * @generated
 */

namespace Com\Youzan\Nova\Framework\Generic\Service;

use Kdt\Iron\Nova\Foundation\Protocol\TStruct;
use Thrift\Type\TType;


class GenericResponse extends TStruct {
  /**
   * @var int
   */
  public $code = null;
  /**
   * @var string
   */
  public $message = null;
  /**
   * @var string
   */
  public $data = null;

  protected $structSpec = [
    1 => [
      'var' => 'code',
      'type' => TType::I32,
      ],
    2 => [
      'var' => 'message',
      'type' => TType::STRING,
      ],
    3 => [
      'var' => 'data',
      'type' => TType::STRING,
      ],
    ];

}

